### ISSUE TITLE
API Exception: 'self_prompt_action'...Retrying...

### ISSUE THREAD

**Issue by MysteriousKnight** [Cytranics/LordGPT#10]
I get this everytime i try a prompt for example: First research good selling halal and legal ebook niche, than write an ebook with the ideal length to sell well and everything else it needs to sell well, finally prepare the files for upload on publish drive and so on.

**Comment by Cytranics** [comment]
Try the latest version, it now generates WAY more content than it used to. I'm also releasing another version later today that fixes a ton of little side cases, but the new prompt additions generated my first full PDF full of HTML. Every day it will get better and better. The mechanics are down. Now its all about prompting.

**Comment by Cytranics** [comment]
Fixed in latest version
