### ISSUE TITLE
After retrieving a webpage it is unable to process it.

### ISSUE THREAD

**Issue by aleks648** [Cytranics/LordGPT#29]
`LordGPT Thoughts: Read the HTML file to extract information about Hiver Beers and their flavour profiles.
Currently :       1.2
Next Task:        If success, move to next subtask item.
Executing CMD:    file_operations
CMD Argument:     hiver_beers.html|```content```|read

⠙ Recruiting LordGPT's party.......Error: This model's maximum context length is 4097 tokens. However, your messages resulted in 449279 tokens. Please reduce the length of the messages.`

**Comment by Cytranics** [comment]
This is fixed.
