### ISSUE TITLE
Mac install errors

### ISSUE THREAD

**Issue by Captain-Bacon** [Cytranics/LordGPT#3]
Unfortunately these commands don't work on a mac either because of file permissions, or 'dpkg' is not a valid command.

wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
sudo mv chromedriver /usr/bin/chromedriver
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo apt-get install -f

**Comment by Cytranics** [comment]
I have a mac, give me a few minutes I'll write out the steps

**Comment by Cytranics** [comment]
> Unfortunately these commands don't work on a mac either because of file permissions, or 'dpkg' is not a valid command.
> 
> wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip unzip chromedriver_linux64.zip sudo mv chromedriver /usr/bin/chromedriver wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb sudo dpkg -i google-chrome-stable_current_amd64.deb sudo apt-get install -f

Skip that part, I forgot I ripped that part out. I'll update instructions.

**Comment by Cytranics** [comment]
Updated README for macs
