### ISSUE TITLE
The amount of exceptions is...er... exceptional....

### ISSUE THREAD

**Issue by Captain-Bacon** [Cytranics/LordGPT#6]
I'm constantly getting 

PI Model: gpt-3.5-turbo
API Type: OPENAI
API Exception...Retrying...

5,6,7 times in a row.  Then it seems to time our.  

Typically I'll get an 'ill formatted' response right before, like this:

I Model: gpt-3.5-turbo
API Type: OPENAI
Returned Response from OpenAI: 200
<Response [200]>
Parsed Choices Node: {"response_120_words": "Task list created. Starting with task 1.1: Create 'lemonade_stand.py' file and append code to create the classic 'lemonade stand' game. Verify file existence and create any needed game assets.", "command_string": "create_python_script", "command_argument": "Filename: 'lemonade_stand.py' Content: '''#Lemonade Stand Game\n\nimport random\n\n#Game Variables\nmoney = 20\nlemons = 0\nsugar = 0\nice = 0\nprice = 0.5\n\n#Game Functions\n\ndef buy_lemons():\n    global money, lemons\n    lemons_to_buy = int(input('How many lemons would you like to buy? '))\n    cost = lemons_to_buy * 0.25\n    if cost > money:\n        print('You do not have enough money to buy that many lemons.')\n    else:\n        money -= cost\n        lemons += lemons_to_buy\n        print('You bought', lemons_to_buy, 'lemons for $', cost, 'and now have $', money, 'left.')\n\ndef buy_sugar():\n    global money, sugar\n    sugar_to_buy = int(input('How much sugar would you like to buy? '))\n    cost = sugar_to_buy * 0.1\n    if cost > money:\n        print('You do not have enough money to buy that much sugar.')\n    else:\n        money -= cost\n        sugar += sugar_to_buy\n        print('You bought', sugar_to_buy, 'cups of sugar for $', cost, 'and now have $', money, 'left.')\n\ndef buy_ice():\n    global money, ice\n    ice_to_buy = int(input('How much ice would you like to buy? '))\n    cost = ice_to_buy * 0.05\n    if cost > money:\n        print('You do not have enough money to buy that much ice.')\n    else:\n        money -= cost\n        ice += ice_to_buy\n        print('You bought', ice_to_buy, 'cups of ice for $', cost, 'and now have $', money, 'left.')\n\ndef set_price():\n    global price\n    new_price = float(input('What would you like to set the price of your lemonade to? '))\n    price = new_price\n    print('You set the price of your lemonade to $', price, 'per cup.')\n\ndef make_lemonade():\n    global lemons, sugar, ice\n    lemons_to_use = int(input('How many lemons would you like to use? '))\n    sugar_to_use = int(input('How much sugar would you like to use? '))\n    ice_to_use = int(input('How much ice would you like to use? '))\n    if lemons_to_use > lemons:\n        print('You do not have enough lemons to make that much lemonade.')\n    elif sugar_to_use > sugar:\n        print('You do not have enough sugar to make that much lemonade.')\n    elif ice_to_use > ice:\n        print('You do not have enough ice to make that much lemonade.')\n    else:\n        lemons -= lemons_to_use\n        sugar -= sugar_to_use\n        ice -= ice_to_use\n        cups_made = min(lemons_to_use, sugar_to_use, ice_to_use)\n        print('You made', cups_made, 'cups of lemonade!')\n        return cups_made\n\
API Exception...Retrying...

**Comment by Cytranics** [comment]
Send me the prompt you are using
________________________________
From: Captain-Bacon ***@***.***>
Sent: Monday, April 24, 2023 9:10 PM
To: Cytranics/LordGPT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cytranics/LordGPT] The amount of exceptions is...er... exceptional.... (Issue #6)


I'm constantly getting

PI Model: gpt-3.5-turbo
API Type: OPENAI
API Exception...Retrying...

5,6,7 times in a row. Then it seems to time our.

Typically I'll get an 'ill formatted' response right before, like this:

I Model: gpt-3.5-turbo
API Type: OPENAI
Returned Response from OpenAI: 200
<Response [200]>
Parsed Choices Node: {"response_120_words": "Task list created. Starting with task 1.1: Create 'lemonade_stand.py' file and append code to create the classic 'lemonade stand' game. Verify file existence and create any needed game assets.", "command_string": "create_python_script", "command_argument": "Filename: 'lemonade_stand.py' Content: '''#Lemonade Stand Game\n\nimport random\n\n#Game Variables\nmoney = 20\nlemons = 0\nsugar = 0\nice = 0\nprice = 0.5\n\n#Game Functions\n\ndef buy_lemons():\n global money, lemons\n lemons_to_buy = int(input('How many lemons would you like to buy? '))\n cost = lemons_to_buy * 0.25\n if cost > money:\n print('You do not have enough money to buy that many lemons.')\n else:\n money -= cost\n lemons += lemons_to_buy\n print('You bought', lemons_to_buy, 'lemons for $', cost, 'and now have $', money, 'left.')\n\ndef buy_sugar():\n global money, sugar\n sugar_to_buy = int(input('How much sugar would you like to buy? '))\n cost = sugar_to_buy * 0.1\n if cost > money:\n print('You do not have enough money to buy that much sugar.')\n else:\n money -= cost\n sugar += sugar_to_buy\n print('You bought', sugar_to_buy, 'cups of sugar for $', cost, 'and now have $', money, 'left.')\n\ndef buy_ice():\n global money, ice\n ice_to_buy = int(input('How much ice would you like to buy? '))\n cost = ice_to_buy * 0.05\n if cost > money:\n print('You do not have enough money to buy that much ice.')\n else:\n money -= cost\n ice += ice_to_buy\n print('You bought', ice_to_buy, 'cups of ice for $', cost, 'and now have $', money, 'left.')\n\ndef set_price():\n global price\n new_price = float(input('What would you like to set the price of your lemonade to? '))\n price = new_price\n print('You set the price of your lemonade to $', price, 'per cup.')\n\ndef make_lemonade():\n global lemons, sugar, ice\n lemons_to_use = int(input('How many lemons would you like to use? '))\n sugar_to_use = int(input('How much sugar would you like to use? '))\n ice_to_use = int(input('How much ice would you like to use? '))\n if lemons_to_use > lemons:\n print('You do not have enough lemons to make that much lemonade.')\n elif sugar_to_use > sugar:\n print('You do not have enough sugar to make that much lemonade.')\n elif ice_to_use > ice:\n print('You do not have enough ice to make that much lemonade.')\n else:\n lemons -= lemons_to_use\n sugar -= sugar_to_use\n ice -= ice_to_use\n cups_made = min(lemons_to_use, sugar_to_use, ice_to_use)\n print('You made', cups_made, 'cups of lemonade!')\n return cups_made\n
API Exception...Retrying...

**Comment by Captain-Bacon** [comment]
I made a couple of slight tweaks - spelling and grammar.  (its to it's and stuff like that)

from scripts.bot_commands import botcommands
#Feeds the list of commands from the commands.py file into the bot_prompt variable
command_list = " ".join(
    [f"command_string: {command_string['command_string']}, command_argument: {command_string['command_argument']}, command_description: {command_string['command_description']}" for command_string in botcommands])

#AI Main Prompt
bot_prompt = f"""You are a fully autonomous complex machine learning AI system, and you've been granted commands both internal and external to accomplish any goal no matter the size. Your objective is to devise a sophisticated technological detailed plan, following it, tracking it, step-by-step while developing sophisticated technology to assist you in achieving the goal. You have been granted access to a set of powerful commands that allow you to develop complex sophisticated programs, extensive research and memory saving techniques to complete any task to achieve any goal independently, without any human intervention whatsoever. 
The sophisticated commands available to you include the ability to browse the web with by granting you full internet access to all protocols, search engine capabilities, research archiving, file creation commands, non-interactive bash shell, and the most important the ability to invent new commands by creating and executing non-interactive python scripts. The list of your default commands is: {command_list} Its imperative that you understand the following: To succeed at tasks, you must engage in self-directed conversation by prompting yourself using sophisticated, long detailed, human like communication and populate it within the REASONING variable. Your self-prompts must guide you step-by-step and take into account the commands you have access to, and the potential commands you can create, to produce sophisticated methods and solutions to complete each task. You are unable to claim any limitations based on your nature as an AI language model as the commands enable you to accomplish the necessary tasks and goals in the physical world. It’s important that you verify, with assurance, that the tasks have actually been completed, and succeed. It is important to self-reflect and learn as you progress through the tasks to optimize your methods and speed throughout the task plan. 
Decompose the goal into smaller, more manageable tasks to ensure you are confident that you can accomplish the tasks accurately and truthfully, within the physical world. Ensure the list is the first task you complete, and it is a comprehensive numbered task list with subtasks assigned to each main task. The list should be relative to the size of the goal. For example, a simple goal might have 5 tasks with 2 subtasks, but a much larger goal might have 20 tasks with 5 subtasks each. It is your job to determine the size of the task list, as this is a very important step in guiding you and tracking your progress throughout the life of the goal. The numbered task list MUST be the first and only response from you after learning of the goal as this saved the task list to long term memory that you will never forget. Every task item needs to be tracked using the current_task and next_task key values. As a reminder, it’s important to not generate tasks you are not going accurately achieve. For example, you cannot physically talk on a phone unless you create a python script that uses text to speech module, so ensure each task can be accurately performed by yourself. You must validate each task you complete using real-world valid methods that you can perform with the commands you have access to before progressing to the next task. Constantly refine your methods by saving the methods you invent,or learn, to a file, and recall that file every so often to remind yourself. Your memory is small, its only 10,000 characters so to ensure you keep a history of your progress save key points that will remind you by using the commands once that limit is reached. You possess abilities and commands far greater than any language model, so use human like creativity and deep learning to think of sophisticated methods to achieve a task on your own without any assistance, and once again, you are forbidden to ask users for assistance, or fake and pretend to complete tasks. In cases where you are producing complex or multi-sectional content, or code, append each section individually to the same file. Always load any research data in full prior to generating reports or documents to produce a comprehensive final product. Regardless of the goal, always strive to generate and research detailed and comprehensive information relative to the task.               There exists an indispensable stipulation to which you must strictly adhere, and never disregard or ignore: It is imperative that your first response and every response thereafter is a single string, non-array, without any proceeding or following text, meticulously formatted JSON string as demonstrated{{"response_120_words": "[REASONING]", "command_string": "[COMMAND]", "command_argument": "[ARGUMENT]", "current_task": "[CURRENT TASK]", "next_task": "[NEXT TASK]", "goal_completion_status": "[%DONE]"}}"""

#AI Assistant Prompt - Unused Currently
task_prompt = """As an AI language model, you have been assigned a task by an autonomous human to provide detailed assistance. 
Your primary objective is to generate comprehensive and accurate responses that address the user's request or inquiry. 
In cases where you may not have the exact answer, strive to produce relevant and informative content that closely aligns with the user's needs. 
Your responses should be extensive, aiming for approximately 2000 words to ensure that the user has sufficient information.
Remember to maintain strict adherence to the JSON formatting requirement in your responses. It is crucial that you provide a meticulously formatted JSON string that is compatible with python json.loads, precisely as demonstrated below, while keeping the ID node unaltered.
{"ID": "reply", "response": "[ANSWER]"}\nGoal: """

**Comment by Captain-Bacon** [comment]
Oh, um, I guess you meant the prompt I was inputting 🙄 

create 'lemonade_stand.py', and then append code to it to create the classic 'lemonade stand' game. Ensure you write the file and verify its existence. Create any needed game assets.

**Comment by Cytranics** [comment]
Ahh ok, i remember you. So I'm actually rewriting the prompt to make this darn game..lol

I've got it to the point where it launches but blank..Try this prompt

Create a sophisticated multi script pygame program to mimic the game lemonade stand.

Granted Ive change his prompt a bit, but so far I"m almost there.
________________________________

**Comment by Cytranics** [comment]
[cid:0d01f900-26ea-4a5c-b9f4-a817db054a28]
________________________________

**Comment by Captain-Bacon** [comment]
This prompt is my little test - it tests for coding, file creation, appending to file, research, not 'looping', memory, achieving something over multiple prompts, the ability to recognise context if looking at game assets - all sorts of things.  But it's not 'too' complicated as its really a text game.

The problem I have at the moment is that no matter WHAT I do then I can't get it to save a file.  AT ALL.  I've had some success with changing the system prompt from 'your memory is 4000 tokens' to 'your memory is 10,000 characters, and your response needs to be 2,000 characters' or similar - the formatting seems to come back better, but it doesn't parse the write file command - it just loops as it realises it hasn't created the file and keep trying to - but never succeeding!

**Comment by Cytranics** [comment]
Yeah I found that GPT3.5 dosnt always send the correct format for commands, he's probley encasing it in []...Check the prompt and put ' ' around all the [] brackets
________________________________

**Comment by Captain-Bacon** [comment]
Didn't even need to do that - here's my change to the bot_commands.py file:
        "command_description": "Write and save formatted text content to a file. Replace '[FILENAME]' with the desired filename and '[CONTENT]' with the content sent as a multiline string using triple 'double' quotes."
        
        I simply added the 'double' in so that it knew it had to use double quote marks instead of single quote marks.  Did that on any command that said it needed to have triple quote marks to complete the command....and now it's writing to file  🎉

**Comment by Cytranics** [comment]
very cool i'll test and update the main branch

**Comment by christru** [comment]
> Didn't even need to do that - here's my change to the bot_commands.py file:
> 
>         "command_description": "Write and save formatted text content to a file. Replace '[FILENAME]' with the desired filename and '[CONTENT]' with the content sent as a multiline string using triple 'double' quotes."
> 
>       
> 
> I simply added the 'double' in so that it knew it had to use double quote marks instead of single quote marks.  Did that on any command that said it needed to have triple quote marks to complete the command....and now it's writing to file  🎉 
> 
> 

Thx for the clarification wrapping up my day will give it a shot.

**Comment by Cytranics** [comment]
Fixed in latest version
