### ISSUE TITLE
Retrying.. error

### ISSUE THREAD

**Issue by purplegold824** [Cytranics/LordGPT#8]
After giving my Goal, it attempts to hit the openai API. Key is set and works everywhere else its been used. unsure how to solve.

**Comment by Cytranics** [comment]
Yup the API's are getting hammered and have frequent timeouts, I get the same thing. Like Christru said, try updating the timeout.

Azure seems to be the best today.

**Comment by Sommos** [comment]
I've found that updating the timeout from 45 seconds to 300 seconds resolved the same issue with me using GPT-3.5-turbo. 90 seconds would result in the same issue. As Cytranics said, Azure is falling over today.

**Comment by Cytranics** [comment]
Bring down your max_token, it should be max of 1000 for gpt3.5

**Comment by Cytranics** [comment]
Fixed in latest version
